ENH: Im not sure if this is required but my tests were previously failing
Installed /Users/iejohnson/.venv/pyradiomics/lib/python3.9/site-packages/pyradiomics-3.1.1-py3.9-macosx-10.9-universal2.egg
Processing dependencies for pyradiomics==3.1.1
Searching for pyradiomics==3.1.1
Reading https://pypi.org/simple/pyradiomics/
No local packages or working download links found for pyradiomics==3.1.1
error: Could not find suitable distribution for Requirement.parse('pyradiomics==3.1.1')

I adjusted the version to be compatable with the versions listed there